blogon: halve wasm bundle size by half
It's still 10x too much, but it's a start.

By using `#[cfg(feature = "ssr")]` and trying to keep all the heavy
SSR stuff out of the WASM bundle, with `pulldown-cmark` in particular.
Hopefully reimplementing that `HeadingLevel` thing help because that's a
lot of slocs…

It feels like I could have organized the code better to have better
separation between the server and client parts.

Note twiggy does not help, I am getting messages like:

```
error: WASM error: invalid flags byte in element segment (at offset 27509)
  caused by: invalid flags byte in element segment (at offset 27509)
 ```

Also bump Rust compiler version (fixes non-release build due to some
nightly changes).